### ISSUE TITLE
how to add a folder with different peoples images for face recognition?

### ISSUE THREAD

**Issue by sunusunu** [amr-khalil/Face-Rcognition-System#1]
I would like to create a directory in this model:
media/
--faces/
---person_1(folder)
-----img1.jpg
-----img2.jpg
---person_2(folder)
-----img1.jpg
-----img2.jpg
---person_3(folder) and so on.

i have also trained a facenet model that can recognize these people with and without a mask, how should I implement it in the current code?
Thanks

**Comment by amr-khalil** [comment]
Just add the image of the person on the faces folder. You must rename the image with the person name. One image will be fine.
